config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[create show]
  resources :items
  resources :categories
  resources :comments, only: [:create]
  
  get "/sign_up", to: "users#new"
  get "/log_in", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"

  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, foreign_key: :category_id, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :category

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :items, foreign_key: :user_id, dependent: :destroy
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end
  
  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to log_in_path unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in?
  def new
    @category = Category.new
  end

  def create
    @category = Category.build(category_params)
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    
    redirect_to root_path, notice: 'The Category was removed from the Store.'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in?

  def new
   @comment = Comment.new
  end

  def create
    @item = Item.find(params[:comment][:item_id])
    comment = @item.comments.build(comment_params)
    comment.user = current_user
    

    if comment.save
      redirect_to comment.item
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    
    redirect_to item_path, notice: 'The comment was deleted.'
  end

private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in?, except: %i[index show]

  def index
    @items = Item.all
    @categories = Category.all
  end
  
  def new
    @item = current_user.items.build
  end

  def create
    @categories = Category.all
    @item = current_user.items.build(items_params)
    
    if @item.save
      redirect_to root_path, notice: 'Item was Add to the Store.'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(book_params)
      redirect_to @item
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    
    redirect_to root_path, notice: 'The item was removed from the Store.'
  end

  private

  def items_params
    params.require(:item).permit(:name, :description, :image_url, :publication_date, :price, :category_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Welcome back!'
    else 
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: 'See you soon'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to root_path notice: 'Welcome!'
    else
      redirect_to :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def creator
  
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1>Create a new Category</h1>

<%= form_for @category do |f| %>
  <%= f.label :name %> <br>
  <%= f.text_field :name, placeholder: "Category Name" %> <br>

  <%= f.submit "Create" %>
<% end %>

app/views/categories/show.html.erb
<h1>Category</h1>
<div><%= @category.name %></div>
<div><%= @category.description %></div>

<h2>Items from this category</h2>

<div> <% @category.items.each do |f| %> 
  <div>
    <%= image_tag(f.image_url) %> <br>
    <%= f.name %> <br>
    <%= f.description %> <br>
    <%= f.price %> <br> 
    <%= link_to "See", f %> <br>
  </div>
<% end %>
</div>

app/views/items/_comments.html.erb
<p>Comments</p>

<% @item.comments.each do |comment| %>
  <p class=""><%= comment.user.username %> wrote <%= distance_of_time_in_words(Time.current, comment.created_at) %> ago</p>
  <div class=""><%= comment.body %></div>
  <% if !current_user.nil? && (comment.user.username == current_user.username) %>
    <%= button_to "Remove", @comment, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>  <br>
  <% end %>
<% end %>

<% if @item.comments.empty? %>
  <p>No one has made a comment yet, be the first one.</p>
<% end %>

<% if logged_in? %>
  <p class="">Leave a Comment.</p>
  <%= form_for @item.comments.build do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.text_area :body, rows: 4, class: "" %>
    <%= f.submit "Post", class: "" %>
  <% end %>
<% else %>
  <p class=""><%= link_to "Sign Up", sign_up_path %> or <%= link_to "Log In", log_in_path %> To leave a Comment.</p>
<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {:prompt => 'Please select a Category'}) %> <br>
    <p> Or   <%= link_to 'Create a New Category',new_category_path %> </p>
  </div>

  <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>
  <div>
    <%= f.label :publication_date %>
    <%= f.date_field :publication_date %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price, step: :any %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form', title: 'Add a New Item to the Store.'%>

app/views/items/index.html.erb
<h1>Store Name</h1>

<% @categories.each do |cat| %>
  <%= link_to cat.name, cat %>
<% end %> <br>


<% if !current_user.nil? %>
  <%= link_to 'Add a Product', new_item_path %> 
  <%= link_to 'Create a New Category',new_category_path %>
<% end %> <br>

  <div>
    <% @items.each do |item| %>
      <%= image_tag(item.image_url, class: 'item-image') %> <br>
      <p class="text-lines"><%= item.name %></p>
      <p class="text-lines"><%= item.user.username %></p>
      <p class="text-lines"><%= item.description %></p>
      <p class="text-lines"><%= item.price %></p>
      <%= link_to "See", item %> <br>
    <% end %>
  </div>

app/views/items/new.html.erb
<%= render 'form', title: 'Add a New Item to the Store.'%>

app/views/items/show.html.erb
<h1>Details of the Item</h1>
<div> <%=image_tag(@item.image_url,class: 'item-image') %> </div>
<div><%= @item.name %></div>
<div>Owner: <%= @item.user.username %></div>
<div>Descripción: <%= @item.description %></div>
<div>Fecha de publicación: <%= @item.publication_date %></div>
<div>Precio: <%= @item.price %></div>
<% if !current_user.nil? && (@item.user.username == current_user.username)   %>
  <%= link_to "Edit", edit_item_path(@item) %>
  <%= link_to "Remove", @item, method: :delete, data: { confirm: "Are you sure you want to delete this item?" } %>  <br>
<% end %>


<%= render 'comments' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemplateStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=''>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <div class="menu">
      <nav>
      <ul>
        <li> <a href="#"><%= link_to 'Home', root_path, method: :get %> </a> </li>
        <% if logged_in? %>
        <li> <a href="#"> <%= link_to "Logout", sessions_path, method: :delete %> </a> </li>
          
        <% else %>
        <li> <a href="" ><%= link_to "Login", log_in_path, method: :get %></a> </li>
        <li> <a href=""> <%= link_to "Sign Up", sign_up_path, method: :get %> </a> </li>
          
        <% end %>
      </ul>
      </nav>
    </div>
  <div class= 'container'>
    <div class="content">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %> <br>
  <%= f.text_field :username, placeholder: "Username" %> <br>
  <%= f.label :email %> <br>
  <%= f.text_field :email, placeholder: "Email" %> <br>
  <%= f.label :password %> <br>
  <%= f.password_field :password, placeholder: "Password" %> <br>
  <%= f.label :password_confirmation %> <br>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %> <br>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>